/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as CallRouteImport } from './routes/call'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LandlordsRouteImport } from './routes/landlords'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronRenewalNoticesRouteImport } from './routes/api/cron/renewal-notices'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordsRoute = LandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRenewalNoticesRoute = ApiCronRenewalNoticesRouteImport.update({
  id: '/api/cron/renewal-notices',
  path: '/api/cron/renewal-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/call': typeof CallRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/about': typeof AboutRoute
  '/landlords': typeof LandlordsRoute
  '/status': typeof StatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/renewal-notices': typeof ApiCronRenewalNoticesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/call': typeof CallRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/about': typeof AboutRoute
  '/landlords': typeof LandlordsRoute
  '/status': typeof StatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/renewal-notices': typeof ApiCronRenewalNoticesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/call': typeof CallRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/about': typeof AboutRoute
  '/landlords': typeof LandlordsRoute
  '/status': typeof StatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/renewal-notices': typeof ApiCronRenewalNoticesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/call'
    | '/jobs'
    | '/login'
    | '/plan'
    | '/about'
    | '/landlords'
    | '/status'
    | '/api/auth/$'
    | '/api/cron/renewal-notices'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/call'
    | '/jobs'
    | '/login'
    | '/plan'
    | '/about'
    | '/landlords'
    | '/status'
    | '/api/auth/$'
    | '/api/cron/renewal-notices'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/call'
    | '/jobs'
    | '/login'
    | '/plan'
    | '/about'
    | '/landlords'
    | '/status'
    | '/api/auth/$'
    | '/api/cron/renewal-notices'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CallRoute: typeof CallRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  AboutRoute: typeof AboutRoute
  LandlordsRoute: typeof LandlordsRoute
  StatusRoute: typeof StatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronRenewalNoticesRoute: typeof ApiCronRenewalNoticesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlords': {
      id: '/landlords'
      path: '/landlords'
      fullPath: '/landlords'
      preLoaderRoute: typeof LandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/renewal-notices': {
      id: '/api/cron/renewal-notices'
      path: '/api/cron/renewal-notices'
      fullPath: '/api/cron/renewal-notices'
      preLoaderRoute: typeof ApiCronRenewalNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CallRoute: CallRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  AboutRoute: AboutRoute,
  LandlordsRoute: LandlordsRoute,
  StatusRoute: StatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronRenewalNoticesRoute: ApiCronRenewalNoticesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
