/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as CallRouteImport } from './routes/call'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LandlordsRouteImport } from './routes/landlords'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as StatusRouteImport } from './routes/status'
import { Route as JobsIdRouteImport } from './routes/jobs_.$id'
import { Route as JobsBooksRouteImport } from './routes/jobs_.books'
import { Route as JobsCustomersRouteImport } from './routes/jobs_.customers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronRenewalNoticesRouteImport } from './routes/api/cron/renewal-notices'
import { Route as ApiReceiptIdRouteImport } from './routes/api/receipt.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordsRoute = LandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs_/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsBooksRoute = JobsBooksRouteImport.update({
  id: '/jobs_/books',
  path: '/jobs/books',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCustomersRoute = JobsCustomersRouteImport.update({
  id: '/jobs_/customers',
  path: '/jobs/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRenewalNoticesRoute = ApiCronRenewalNoticesRouteImport.update({
  id: '/api/cron/renewal-notices',
  path: '/api/cron/renewal-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptIdRoute = ApiReceiptIdRouteImport.update({
  id: '/api/receipt/$id',
  path: '/api/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/call': typeof CallRoute
  '/jobs': typeof JobsRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/status': typeof StatusRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/books': typeof JobsBooksRoute
  '/jobs/customers': typeof JobsCustomersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/renewal-notices': typeof ApiCronRenewalNoticesRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/call': typeof CallRoute
  '/jobs': typeof JobsRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/status': typeof StatusRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/books': typeof JobsBooksRoute
  '/jobs/customers': typeof JobsCustomersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/renewal-notices': typeof ApiCronRenewalNoticesRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/call': typeof CallRoute
  '/jobs': typeof JobsRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/status': typeof StatusRoute
  '/jobs_/$id': typeof JobsIdRoute
  '/jobs_/books': typeof JobsBooksRoute
  '/jobs_/customers': typeof JobsCustomersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/renewal-notices': typeof ApiCronRenewalNoticesRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/call'
    | '/jobs'
    | '/landlords'
    | '/login'
    | '/plan'
    | '/status'
    | '/jobs/$id'
    | '/jobs/books'
    | '/jobs/customers'
    | '/api/auth/$'
    | '/api/cron/renewal-notices'
    | '/api/receipt/$id'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/call'
    | '/jobs'
    | '/landlords'
    | '/login'
    | '/plan'
    | '/status'
    | '/jobs/$id'
    | '/jobs/books'
    | '/jobs/customers'
    | '/api/auth/$'
    | '/api/cron/renewal-notices'
    | '/api/receipt/$id'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/call'
    | '/jobs'
    | '/landlords'
    | '/login'
    | '/plan'
    | '/status'
    | '/jobs_/$id'
    | '/jobs_/books'
    | '/jobs_/customers'
    | '/api/auth/$'
    | '/api/cron/renewal-notices'
    | '/api/receipt/$id'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CallRoute: typeof CallRoute
  JobsRoute: typeof JobsRoute
  LandlordsRoute: typeof LandlordsRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  StatusRoute: typeof StatusRoute
  JobsIdRoute: typeof JobsIdRoute
  JobsBooksRoute: typeof JobsBooksRoute
  JobsCustomersRoute: typeof JobsCustomersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronRenewalNoticesRoute: typeof ApiCronRenewalNoticesRoute
  ApiReceiptIdRoute: typeof ApiReceiptIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlords': {
      id: '/landlords'
      path: '/landlords'
      fullPath: '/landlords'
      preLoaderRoute: typeof LandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$id': {
      id: '/jobs_/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/books': {
      id: '/jobs_/books'
      path: '/jobs/books'
      fullPath: '/jobs/books'
      preLoaderRoute: typeof JobsBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/customers': {
      id: '/jobs_/customers'
      path: '/jobs/customers'
      fullPath: '/jobs/customers'
      preLoaderRoute: typeof JobsCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/renewal-notices': {
      id: '/api/cron/renewal-notices'
      path: '/api/cron/renewal-notices'
      fullPath: '/api/cron/renewal-notices'
      preLoaderRoute: typeof ApiCronRenewalNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipt/$id': {
      id: '/api/receipt/$id'
      path: '/api/receipt/$id'
      fullPath: '/api/receipt/$id'
      preLoaderRoute: typeof ApiReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CallRoute: CallRoute,
  JobsRoute: JobsRoute,
  LandlordsRoute: LandlordsRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  StatusRoute: StatusRoute,
  JobsIdRoute: JobsIdRoute,
  JobsBooksRoute: JobsBooksRoute,
  JobsCustomersRoute: JobsCustomersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronRenewalNoticesRoute: ApiCronRenewalNoticesRoute,
  ApiReceiptIdRoute: ApiReceiptIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
